### PR TITLE
WP-75 if responsive player, use percentage for height

### PR DESCRIPTION
**Pull request by muli**

### CODE REVIEW

**Comment by rkreich** [comment]
@muli, seeing that the spacer calculation was removed, are we assuming that all players are chromeless?

**Comment by muli** [comment]
@rkreich - yes, kind of.
The idea is that when a user selects a player size, the size of the player will be exactly as stated in the player selection screen. Meaning, if a user chose that the player will be 400x300, the player will take 400x300 of the post, whether the controls bar is part of the player or not (i.e. the player is defined with hovering controls).

**Comment by rkreich** [comment]
@muli, it means that non chromeless players would have black borders, which looks bad.. Can you provide Zohar with a few screenshots of chromless vs regular players? just to make sure that he understands how this is going to look.

**Comment by muli** [comment]
@rkreich - you're right. please see my latest commit, which adds 36px if the player is not chromeless.

**Comment by rkreich** [comment]
OK.
Are you fine with hard-coding it to 36px? All default players have 36px control bar?

**Comment by muli** [comment]
I believe so.
Would you do something else instead?

**Comment by rkreich** [comment]
I see that you are checking against the actual player if hovering controls are visible. Maybe it would be possible to check the actual height of the control bar.

**Comment by muli** [comment]
I don't think it's possible, I believe that it's in the player core CSS...

**Pull request merged**
