### PR TITLE
Additional curl configuration options

### PR DESCRIPTION
**Pull request by jdub233**
This PR adds a filter (`kaltura_client_config_filter`) to the client configuration so that the CURL options can be customized without needing to patch the source code in the plugin.

It also adds proxy tunnel as a configurable value, so that tunneling can be optionally turned off.

### CODE REVIEW

**Comment by rkreich** [comment]
Hi @jdub233,
`Kaltura_Client_Configuration` is taken from another repo (https://github.com/kaltura/clients-generator/tree/Lynx-12.15.0/sources/zend)
This needs to be change here (at first): https://github.com/kaltura/clients-generator/blob/f3026978112562f03d90884af901f9193c6e6abc/sources/zend/Kaltura/Client/ClientBase.php#L393

Thanks

**Comment by jdub233** [comment]
Hi @rkreich,

Thanks, I've submitted a separate PR in that repo for the config changes:
https://github.com/kaltura/clients-generator/pull/106

Sounds like I should also remove those changes from this branch.

**Comment by rkreich** [comment]
Thanks @jdub233 

@jessp01, do you think that we can setup another repo to generate WP client library based on the following config https://github.com/kaltura/all-in-one-video-pack.wordpress/blob/master/lib/Kaltura/client-generation-readme.txt ?

**Comment by jessp01** [comment]
Hi @rkreich,
We can. Make a pull request to https://github.com/kaltura/clients-generator/tree/Lynx-12.15.0/config and once that's done, I can use it to generate a 'wordpress' client as part of the CI and push it to a dedicated repo.

**Comment by rkreich** [comment]
Hi @jessp01,
Does all client repos are based on the configs from https://github.com/kaltura/clients-generator/tree/Lynx-12.15.0/config?

**Comment by jessp01** [comment]
Hi @rkreich,

Yes, I simply iterate over all clients listed in https://github.com/kaltura/clients-generator/blob/Lynx-12.15.0/config/generator.all.ini

**Comment by jessp01** [comment]
@rkreich, @jdub233, I see https://github.com/kaltura/clients-generator/pull/106 was merged. Can we close this one?

**Comment by rkreich** [comment]
@jessp01, we also need to update the Kaltura client library in WordPress, unfortunately the latest code of  client generator produces huge diff, which I don't want to merge. I found a few issues in the generator which causes this diff, but I don't have enough time to fix it.

**Comment by jessp01** [comment]
Hi @rkreich, understood:) but either way, it shouldn't be merged directly into this repo so I still think this pull should be closed.. perhaps we can add an issue noting this is pending resolution instead?

**Comment by rkreich** [comment]
Created new issue for client library upgrade: https://github.com/kaltura/all-in-one-video-pack.wordpress/issues/59

**Pull request merged**
